version: '3.8'
services:
  student-db:
    image: postgres:15
    container_name: student-db
    environment:
      POSTGRES_USER: studentuser
      POSTGRES_PASSWORD: studentpass
      POSTGRES_DB: studentsdb
    ports:
      - "5000:5000"
    volumes:
      - ./student-profile/init.sql:/docker-entrypoint-initdb.d/init.sql

  student-profile:
    build: ./student-profile
    container_name: student-profile
    environment:
      - DATABASE_URL=postgres://studentuser:studentpass@student-db:5000/studentsdb
    depends_on:
      - student-db
    ports:
      - "5001:5001"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - student-profile